#pragma once
#include "cinder/CinderResources.h"

#define RES_LANDSCAPE_OBJ              "landscape-split.obj"
#define RES_EPHEM_SCRIPT               "ephemScript.py"

// Deferred Renderer
#define RES_TEX_NOISE_SAMPLER          "CinderDeferredResources/textures/random.png"
#define RES_GLSL_ALPHA_RGB_VERT        "CinderDeferredResources/shaders/AlphaToRGB_glsl.vert"
#define RES_GLSL_ALPHA_RGB_FRAG        "CinderDeferredResources/shaders/AlphaToRGB_glsl.frag"
#define RES_GLSL_BASIC_BLENDER_VERT    "CinderDeferredResources/shaders/BasicBlender_glsl.vert"
#define RES_GLSL_BASIC_BLENDER_FRAG    "CinderDeferredResources/shaders/BasicBlender_glsl.frag"
#define RES_GLSL_BLUR_H_VERT           "CinderDeferredResources/shaders/Blur_h_glsl.vert"
#define RES_GLSL_BLUR_H_FRAG           "CinderDeferredResources/shaders/Blur_h_glsl.frag"
#define RES_GLSL_BLUR_V_VERT           "CinderDeferredResources/shaders/Blur_v_glsl.vert"
#define RES_GLSL_BLUR_V_FRAG           "CinderDeferredResources/shaders/Blur_v_glsl.frag"
#define RES_GLSL_CUBESHADOW_VERT       "CinderDeferredResources/shaders/CubeShadowMap_glsl.vert"
#define RES_GLSL_CUBESHADOW_FRAG       "CinderDeferredResources/shaders/CubeShadowMap_glsl.frag"
#define RES_GLSL_DEFER_VERT            "CinderDeferredResources/shaders/Deferred_glsl.vert"
#define RES_GLSL_DEFER_FRAG            "CinderDeferredResources/shaders/Deferred_glsl.frag"
#define RES_GLSL_FXAA_VERT             "CinderDeferredResources/shaders/FXAA_glsl.vert"
#define RES_GLSL_FXAA_FRAG             "CinderDeferredResources/shaders/FXAA_glsl.frag"
#define RES_GLSL_LIGHT_VERT            "CinderDeferredResources/shaders/Light_glsl.vert"
#define RES_GLSL_LIGHT_FRAG            "CinderDeferredResources/shaders/Light_glsl.frag"
#define RES_GLSL_SSAO_VERT             "CinderDeferredResources/shaders/SSAO_glsl.vert"
#define RES_GLSL_SSAO_FRAG             "CinderDeferredResources/shaders/SSAO_glsl.frag"
